### ISSUE TITLE
Zero size arrays and flexible array members

### ISSUE THREAD

**Issue by jennybc** [evanmiller/libxls#15]
Re: manual patches applied in readxl when we pull from upstream libxls and [whether the need can be designed away](https://github.com/evanmiller/libxls/issues/11#issuecomment-381294447).

readxl gets built with a C++ compiler and with flags dictated by CRAN.

We get several warnings about zero size arrays and flexible array members. One example:

```
./libxls/xlsstruct.h:126:10: warning: flexible array members are a C99 feature [-Wc99-extensions]
    char        name[];
                ^
```

And another:

```
./libxls/xlsstruct.h:243:18: warning: zero size arrays are an extension [-Wzero-length-array]
    BYTE        strings[0];
                        ^
```

This has been true for a long time, certainly before I even took over as maintainer. Our traditional "solution" has been to replace every instance of `thing[]` or `thing[0]` with `thing[1]`. After the most recent wave of changes, this hack is no longer an option. Although readxl compiles with these changes, we get segfaults or nonsense in some of our tests and examples.

@jimhester is helping me work around this for the current readxl release, but I wanted to open a conversation about working towards a better mutual solution in the future.

**Comment by jennybc** [comment]
Parking a couple of links shared by @jimhester here, for my own benefit if nothing else:

[SO post "variable length structures in C90"](https://stackoverflow.com/questions/23093220/variable-length-structures-in-c90/23093435#23093435)

[Constructs valid in C but not in C++](https://en.wikipedia.org/wiki/Compatibility_of_C_and_C%2B%2B#Constructs_valid_in_C_but_not_in_C++)

[SO post "Does extern C with C++ avoid undefined behavior that is legal in C but not C++?"](https://stackoverflow.com/questions/31881811/does-extern-c-with-c-avoid-undefined-behavior-that-is-legal-in-c-but-not-c/31881926#31881926)

**Comment by evanmiller** [comment]
Thanks for bringing this issue to my attention.

Parts of the code depend on the result of `sizeof` for structures with flexible arrays, which may explain why segfaults are happening when you change `[0]` or `[]` to `[1]`.

I'm certainly amenable to adapting the code to be C++ compatible, since libxls bills itself as a C/C++ library. However, removing the flexible / zero-sized arrays may require a non-trivial amount of work. I count ten usages of flexible arrays in master; every usage of each of these ten structs will need to be examined. The libxls test suite is rather cursory, so I'm afraid it won't be sufficient to add a bunch of `[1]` arrays, fix the test failures, and call it a day.

Flexible and zero-sized arrays appear to have been in the code base for a long time, so I'm guessing C++ compatibility fell by the wayside rather far up the river. Restoring it is not a high priority for me; I will gladly accept a patch that has been thoroughly tested, but in the absence of such a patch, I will be forced to advertise the upcoming release as a C-only library.

**Comment by jennybc** [comment]
I know these 10 locations by heart now 🙂

We're releasing "as is" and are just debating between two competing approaches to getting out ahead of the inevitable CRAN notes.

We'll discuss the more substantive long-term outlook and get back in touch. Thanks!

**Comment by jennybc** [comment]
This looks great!

I get a clean R CMD check everywhere (local macOS, travis = several versions of R * linux/macOS, AppVeyor, local Windows 10 VM).

I also note and celebrate that other recent changes in master have cleared another warning I hadn't brought up yet ("dereferencing type-punned pointer will break strict-aliasing rules").

**Comment by evanmiller** [comment]
Thanks for the report. The changes so far have been rolled into master. I'm going to close this issue; please open a new issue for any remaining C++ problems that crop up.
